### ISSUE TITLE
Note, figure/table/equation in-text styling is also customisable

### ISSUE THREAD

**Issue by rvanmazijk** [rvanmazijk/Cape-vs-SWA#35]
Using `_bookdown.yml`, you can specify how these things appear in text before a `bookdown` `\@ref()`-call. See <https://bookdown.org/yihui/bookdown/internationalization.html> for more (copied YAML below.

```yml
language:
  label:
    fig: 'Figure '
    tab: 'Table '
    eq: 'Equation '
```

Or rather, if you wish:

```yml
language:
  label:
    fig: 'Fig. '
    tab: 'Table '
    eq: 'Eqn. '
```
